[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = espidf
monitor_speed = 115200

board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
upload_protocol = esptool
monitor_filters = esp32_exception_decoder

build_unflags = 
    -Werror
    -Wno-old-style-declaration
    -fuse-cxa-atexit

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -I include  