// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef _UI_COMP_LOGOIMAGE_H
#define _UI_COMP_LOGOIMAGE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LogoImage
#define UI_COMP_LOGOIMAGE_LOGOIMAGE 0
#define _UI_COMP_LOGOIMAGE_NUM 1
lv_obj_t * ui_LogoImage_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
