// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void wifimenu_dropdown_handler(lv_event_t * e);
void WIFIConnectHandler(lv_event_t * e);
void ToggleFileDump(lv_event_t * e);
void TogglePacketLog(lv_event_t * e);
void ToggleDeviceInv(lv_event_t * e);
void TargetDeviceMAC(lv_event_t * e);
void ToggleCaptivePortal(lv_event_t * e);
void ToggleSSIDSpam(lv_event_t * e);
void RandomizeMAC(lv_event_t * e);
void StartMACSpoofing(lv_event_t * e);
void StartDeauth(lv_event_t * e);
void ScanNetworks(lv_event_t * e);
void RetrieveSSID(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
