// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_IR_MENU = NULL;
lv_obj_t * ui_StatusBarIR = NULL;
lv_obj_t * ui_BatteryTextIR = NULL;
lv_obj_t * ui_WIFI6 = NULL;
lv_obj_t * ui_NOWIFI6 = NULL;
lv_obj_t * ui_BLUETOOTH6 = NULL;
lv_obj_t * ui_NOBLUETOOTH6 = NULL;
lv_obj_t * ui_Back_Button5 = NULL;
lv_obj_t * ui_Menu_Name5 = NULL;
lv_obj_t * ui_Battery_Bar6 = NULL;
lv_obj_t * ui_IR_Options = NULL;
// event funtions
void ui_event_Back_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
    }
}

// build funtions

void ui_IR_MENU_screen_init(void)
{
    ui_IR_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IR_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarIR = lv_obj_create(ui_IR_MENU);
    lv_obj_remove_style_all(ui_StatusBarIR);
    lv_obj_set_width(ui_StatusBarIR, 241);
    lv_obj_set_height(ui_StatusBarIR, 11);
    lv_obj_set_x(ui_StatusBarIR, 0);
    lv_obj_set_y(ui_StatusBarIR, -155);
    lv_obj_set_align(ui_StatusBarIR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarIR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarIR, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarIR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextIR = lv_label_create(ui_IR_MENU);
    lv_obj_set_width(ui_BatteryTextIR, 52);
    lv_obj_set_height(ui_BatteryTextIR, 13);
    lv_obj_set_x(ui_BatteryTextIR, 87);
    lv_obj_set_y(ui_BatteryTextIR, -154);
    lv_obj_set_align(ui_BatteryTextIR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextIR, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextIR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI6 = lv_img_create(ui_IR_MENU);
    lv_img_set_src(ui_WIFI6, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI6, 205);
    lv_obj_set_height(ui_WIFI6, 188);
    lv_obj_set_x(ui_WIFI6, -109);
    lv_obj_set_y(ui_WIFI6, -161);
    lv_obj_set_align(ui_WIFI6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI6, 14);

    ui_NOWIFI6 = lv_img_create(ui_IR_MENU);
    lv_img_set_src(ui_NOWIFI6, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI6, 201);
    lv_obj_set_height(ui_NOWIFI6, 194);
    lv_obj_set_x(ui_NOWIFI6, -111);
    lv_obj_set_y(ui_NOWIFI6, -158);
    lv_obj_set_align(ui_NOWIFI6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI6, 14);

    ui_BLUETOOTH6 = lv_img_create(ui_IR_MENU);
    lv_img_set_src(ui_BLUETOOTH6, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH6, 211);
    lv_obj_set_height(ui_BLUETOOTH6, 192);
    lv_obj_set_x(ui_BLUETOOTH6, -91);
    lv_obj_set_y(ui_BLUETOOTH6, -159);
    lv_obj_set_align(ui_BLUETOOTH6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH6, 14);

    ui_NOBLUETOOTH6 = lv_img_create(ui_IR_MENU);
    lv_img_set_src(ui_NOBLUETOOTH6, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH6, 199);
    lv_obj_set_height(ui_NOBLUETOOTH6, 199);
    lv_obj_set_x(ui_NOBLUETOOTH6, -97);
    lv_obj_set_y(ui_NOBLUETOOTH6, -156);
    lv_obj_set_align(ui_NOBLUETOOTH6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH6, 14);

    ui_Back_Button5 = lv_btn_create(ui_IR_MENU);
    lv_obj_set_width(ui_Back_Button5, 20);
    lv_obj_set_height(ui_Back_Button5, 20);
    lv_obj_set_x(ui_Back_Button5, -107);
    lv_obj_set_y(ui_Back_Button5, -136);
    lv_obj_set_align(ui_Back_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button5, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name5 = lv_label_create(ui_IR_MENU);
    lv_obj_set_width(ui_Menu_Name5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name5, 0);
    lv_obj_set_y(ui_Menu_Name5, -136);
    lv_obj_set_align(ui_Menu_Name5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name5, "IR MENU");
    lv_obj_set_style_text_decor(ui_Menu_Name5, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar6 = lv_bar_create(ui_IR_MENU);
    lv_bar_set_value(ui_Battery_Bar6, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar6, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar6, 22);
    lv_obj_set_height(ui_Battery_Bar6, 9);
    lv_obj_set_x(ui_Battery_Bar6, 100);
    lv_obj_set_y(ui_Battery_Bar6, -155);
    lv_obj_set_align(ui_Battery_Bar6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar6, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar6, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar6, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar6, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_IR_Options = lv_dropdown_create(ui_IR_MENU);
    lv_dropdown_set_options(ui_IR_Options, "Transmit\nRecieve\nUniversal Remote\nJammer\nBeacon\nReplay");
    lv_obj_set_width(ui_IR_Options, 233);
    lv_obj_set_height(ui_IR_Options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IR_Options, -1);
    lv_obj_set_y(ui_IR_Options, -103);
    lv_obj_set_align(ui_IR_Options, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IR_Options, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_Back_Button5, ui_event_Back_Button5, LV_EVENT_ALL, NULL);

}

void ui_IR_MENU_screen_destroy(void)
{
    if(ui_IR_MENU) lv_obj_del(ui_IR_MENU);

    // NULL screen variables
    ui_IR_MENU = NULL;
    ui_StatusBarIR = NULL;
    ui_BatteryTextIR = NULL;
    ui_WIFI6 = NULL;
    ui_NOWIFI6 = NULL;
    ui_BLUETOOTH6 = NULL;
    ui_NOBLUETOOTH6 = NULL;
    ui_Back_Button5 = NULL;
    ui_Menu_Name5 = NULL;
    ui_Battery_Bar6 = NULL;
    ui_IR_Options = NULL;

}
