// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_MENU = NULL;
lv_obj_t * ui_StatusBar = NULL;
lv_obj_t * ui_BatteryText = NULL;
lv_obj_t * ui_WIFI = NULL;
lv_obj_t * ui_NOWIFI = NULL;
lv_obj_t * ui_BLUETOOTH = NULL;
lv_obj_t * ui_NOBLUETOOTH = NULL;
lv_obj_t * ui_WIFI_BTN = NULL;
lv_obj_t * ui_WIFIIcon = NULL;
lv_obj_t * ui_BLUETOOTH_BTN = NULL;
lv_obj_t * ui_BLEIcon = NULL;
lv_obj_t * ui_NFC_BTN = NULL;
lv_obj_t * ui_NFCIcon = NULL;
lv_obj_t * ui_RFID_BTN = NULL;
lv_obj_t * ui_RFIDIcon = NULL;
lv_obj_t * ui_IR_BTN = NULL;
lv_obj_t * ui_IRIcon = NULL;
lv_obj_t * ui_RF_BTN = NULL;
lv_obj_t * ui_RFIcon = NULL;
lv_obj_t * ui_Battery_Bar = NULL;
// event funtions
void ui_event_WIFI_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WIFI_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WIFI_MENU_screen_init);
    }
}

void ui_event_BLUETOOTH_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BLUETOOTH_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_BLUETOOTH_MENU_screen_init);
    }
}

void ui_event_NFC_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NFC_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_NFC_MENU_screen_init);
    }
}

void ui_event_RFID_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RFID_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_RFID_MENU_screen_init);
    }
}

void ui_event_IR_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IR_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_IR_MENU_screen_init);
    }
}

void ui_event_RF_BTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RF_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_RF_MENU_screen_init);
    }
}

// build funtions

void ui_MENU_screen_init(void)
{
    ui_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MENU, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MENU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBar = lv_obj_create(ui_MENU);
    lv_obj_remove_style_all(ui_StatusBar);
    lv_obj_set_width(ui_StatusBar, 241);
    lv_obj_set_height(ui_StatusBar, 11);
    lv_obj_set_x(ui_StatusBar, 0);
    lv_obj_set_y(ui_StatusBar, -155);
    lv_obj_set_align(ui_StatusBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBar, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryText = lv_label_create(ui_MENU);
    lv_obj_set_width(ui_BatteryText, 52);
    lv_obj_set_height(ui_BatteryText, 13);
    lv_obj_set_x(ui_BatteryText, 87);
    lv_obj_set_y(ui_BatteryText, -154);
    lv_obj_set_align(ui_BatteryText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryText, "100%");
    lv_obj_set_style_text_font(ui_BatteryText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI = lv_img_create(ui_MENU);
    lv_img_set_src(ui_WIFI, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI, 205);
    lv_obj_set_height(ui_WIFI, 188);
    lv_obj_set_x(ui_WIFI, -109);
    lv_obj_set_y(ui_WIFI, -161);
    lv_obj_set_align(ui_WIFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI, 14);

    ui_NOWIFI = lv_img_create(ui_MENU);
    lv_img_set_src(ui_NOWIFI, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI, 201);
    lv_obj_set_height(ui_NOWIFI, 194);
    lv_obj_set_x(ui_NOWIFI, -111);
    lv_obj_set_y(ui_NOWIFI, -158);
    lv_obj_set_align(ui_NOWIFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI, 14);

    ui_BLUETOOTH = lv_img_create(ui_MENU);
    lv_img_set_src(ui_BLUETOOTH, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH, 211);
    lv_obj_set_height(ui_BLUETOOTH, 192);
    lv_obj_set_x(ui_BLUETOOTH, -91);
    lv_obj_set_y(ui_BLUETOOTH, -159);
    lv_obj_set_align(ui_BLUETOOTH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH, 14);

    ui_NOBLUETOOTH = lv_img_create(ui_MENU);
    lv_img_set_src(ui_NOBLUETOOTH, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH, 199);
    lv_obj_set_height(ui_NOBLUETOOTH, 199);
    lv_obj_set_x(ui_NOBLUETOOTH, -97);
    lv_obj_set_y(ui_NOBLUETOOTH, -156);
    lv_obj_set_align(ui_NOBLUETOOTH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH, 14);

    ui_WIFI_BTN = lv_btn_create(ui_MENU);
    lv_obj_set_width(ui_WIFI_BTN, 70);
    lv_obj_set_height(ui_WIFI_BTN, 70);
    lv_obj_set_x(ui_WIFI_BTN, 5);
    lv_obj_set_y(ui_WIFI_BTN, 18);
    lv_obj_add_flag(ui_WIFI_BTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFI_BTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFI_BTN, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFI_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIIcon = lv_img_create(ui_WIFI_BTN);
    lv_img_set_src(ui_WIFIIcon, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFIIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFIIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WIFIIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFIIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFIIcon, 75);

    ui_BLUETOOTH_BTN = lv_btn_create(ui_MENU);
    lv_obj_set_width(ui_BLUETOOTH_BTN, 70);
    lv_obj_set_height(ui_BLUETOOTH_BTN, 70);
    lv_obj_set_x(ui_BLUETOOTH_BTN, 0);
    lv_obj_set_y(ui_BLUETOOTH_BTN, -107);
    lv_obj_set_align(ui_BLUETOOTH_BTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH_BTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH_BTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLUETOOTH_BTN, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLUETOOTH_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLEIcon = lv_img_create(ui_BLUETOOTH_BTN);
    lv_img_set_src(ui_BLEIcon, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLEIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLEIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BLEIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLEIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLEIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLEIcon, 75);

    ui_NFC_BTN = lv_btn_create(ui_MENU);
    lv_obj_set_width(ui_NFC_BTN, 70);
    lv_obj_set_height(ui_NFC_BTN, 70);
    lv_obj_set_x(ui_NFC_BTN, 80);
    lv_obj_set_y(ui_NFC_BTN, -107);
    lv_obj_set_align(ui_NFC_BTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NFC_BTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NFC_BTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NFC_BTN, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NFC_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NFCIcon = lv_img_create(ui_NFC_BTN);
    lv_img_set_src(ui_NFCIcon, &ui_img_nfc_png);
    lv_obj_set_width(ui_NFCIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NFCIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NFCIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NFCIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NFCIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NFCIcon, 75);

    ui_RFID_BTN = lv_btn_create(ui_MENU);
    lv_obj_set_width(ui_RFID_BTN, 70);
    lv_obj_set_height(ui_RFID_BTN, 70);
    lv_obj_set_x(ui_RFID_BTN, 5);
    lv_obj_set_y(ui_RFID_BTN, 97);
    lv_obj_add_flag(ui_RFID_BTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RFID_BTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RFID_BTN, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RFID_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDIcon = lv_img_create(ui_RFID_BTN);
    lv_img_set_src(ui_RFIDIcon, &ui_img_rfid_png);
    lv_obj_set_width(ui_RFIDIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIDIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RFIDIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RFIDIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RFIDIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_RFIDIcon, 75);

    ui_IR_BTN = lv_btn_create(ui_MENU);
    lv_obj_set_width(ui_IR_BTN, 70);
    lv_obj_set_height(ui_IR_BTN, 70);
    lv_obj_set_x(ui_IR_BTN, 85);
    lv_obj_set_y(ui_IR_BTN, 97);
    lv_obj_add_flag(ui_IR_BTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IR_BTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IR_BTN, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IR_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IRIcon = lv_img_create(ui_IR_BTN);
    lv_img_set_src(ui_IRIcon, &ui_img_ir_png);
    lv_obj_set_width(ui_IRIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IRIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IRIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IRIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IRIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IRIcon, 75);

    ui_RF_BTN = lv_btn_create(ui_MENU);
    lv_obj_set_width(ui_RF_BTN, 70);
    lv_obj_set_height(ui_RF_BTN, 70);
    lv_obj_set_x(ui_RF_BTN, 165);
    lv_obj_set_y(ui_RF_BTN, 97);
    lv_obj_add_flag(ui_RF_BTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RF_BTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RF_BTN, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RF_BTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIcon = lv_img_create(ui_RF_BTN);
    lv_img_set_src(ui_RFIcon, &ui_img_rf_png);
    lv_obj_set_width(ui_RFIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RFIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RFIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RFIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_RFIcon, 75);

    ui_Battery_Bar = lv_bar_create(ui_MENU);
    lv_bar_set_value(ui_Battery_Bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar, 22);
    lv_obj_set_height(ui_Battery_Bar, 9);
    lv_obj_set_x(ui_Battery_Bar, 100);
    lv_obj_set_y(ui_Battery_Bar, -155);
    lv_obj_set_align(ui_Battery_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WIFI_BTN, ui_event_WIFI_BTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLUETOOTH_BTN, ui_event_BLUETOOTH_BTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NFC_BTN, ui_event_NFC_BTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RFID_BTN, ui_event_RFID_BTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IR_BTN, ui_event_IR_BTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RF_BTN, ui_event_RF_BTN, LV_EVENT_ALL, NULL);

}

void ui_MENU_screen_destroy(void)
{
    if(ui_MENU) lv_obj_del(ui_MENU);

    // NULL screen variables
    ui_MENU = NULL;
    ui_StatusBar = NULL;
    ui_BatteryText = NULL;
    ui_WIFI = NULL;
    ui_NOWIFI = NULL;
    ui_BLUETOOTH = NULL;
    ui_NOBLUETOOTH = NULL;
    ui_WIFI_BTN = NULL;
    ui_WIFIIcon = NULL;
    ui_BLUETOOTH_BTN = NULL;
    ui_BLEIcon = NULL;
    ui_NFC_BTN = NULL;
    ui_NFCIcon = NULL;
    ui_RFID_BTN = NULL;
    ui_RFIDIcon = NULL;
    ui_IR_BTN = NULL;
    ui_IRIcon = NULL;
    ui_RF_BTN = NULL;
    ui_RFIcon = NULL;
    ui_Battery_Bar = NULL;

}
