// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MENU
extern void ui_MENU_screen_init(void);
extern void ui_MENU_screen_destroy(void);
extern lv_obj_t * ui_MENU;
extern lv_obj_t * ui_StatusBar;
extern lv_obj_t * ui_BatteryText;
extern lv_obj_t * ui_WIFI;
extern lv_obj_t * ui_NOWIFI;
extern lv_obj_t * ui_BLUETOOTH;
extern lv_obj_t * ui_NOBLUETOOTH;
extern void ui_event_WIFI_BTN(lv_event_t * e);
extern lv_obj_t * ui_WIFI_BTN;
extern lv_obj_t * ui_WIFIIcon;
extern void ui_event_BLUETOOTH_BTN(lv_event_t * e);
extern lv_obj_t * ui_BLUETOOTH_BTN;
extern lv_obj_t * ui_BLEIcon;
extern void ui_event_NFC_BTN(lv_event_t * e);
extern lv_obj_t * ui_NFC_BTN;
extern lv_obj_t * ui_NFCIcon;
extern void ui_event_RFID_BTN(lv_event_t * e);
extern lv_obj_t * ui_RFID_BTN;
extern lv_obj_t * ui_RFIDIcon;
extern void ui_event_IR_BTN(lv_event_t * e);
extern lv_obj_t * ui_IR_BTN;
extern lv_obj_t * ui_IRIcon;
extern void ui_event_RF_BTN(lv_event_t * e);
extern lv_obj_t * ui_RF_BTN;
extern lv_obj_t * ui_RFIcon;
extern lv_obj_t * ui_Battery_Bar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

