// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_NFC_MENU_H
#define UI_NFC_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NFC_MENU
extern void ui_NFC_MENU_screen_init(void);
extern void ui_NFC_MENU_screen_destroy(void);
extern lv_obj_t * ui_NFC_MENU;
extern lv_obj_t * ui_StatusBarNFC;
extern lv_obj_t * ui_BatteryTextNFC;
extern lv_obj_t * ui_WIFI4;
extern lv_obj_t * ui_NOWIFI4;
extern lv_obj_t * ui_BLUETOOTH4;
extern lv_obj_t * ui_NOBLUETOOTH4;
extern void ui_event_Back_Button3(lv_event_t * e);
extern lv_obj_t * ui_Back_Button3;
extern lv_obj_t * ui_Menu_Name3;
extern lv_obj_t * ui_Battery_Bar4;
extern lv_obj_t * ui_NFC_Options;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

