// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_RFID_MENU_H
#define UI_RFID_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RFID_MENU
extern void ui_RFID_MENU_screen_init(void);
extern void ui_RFID_MENU_screen_destroy(void);
extern lv_obj_t * ui_RFID_MENU;
extern lv_obj_t * ui_StatusBarRFID;
extern lv_obj_t * ui_BatteryTextRFID;
extern lv_obj_t * ui_WIFI5;
extern lv_obj_t * ui_NOWIFI5;
extern lv_obj_t * ui_BLUETOOTH5;
extern lv_obj_t * ui_NOBLUETOOTH5;
extern void ui_event_Back_Button4(lv_event_t * e);
extern lv_obj_t * ui_Back_Button4;
extern lv_obj_t * ui_Menu_Name4;
extern lv_obj_t * ui_Battery_Bar5;
extern lv_obj_t * ui_RFID_Options;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

