// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef _FLIPPER_INFINITY_SCREEN_UI_H
#define _FLIPPER_INFINITY_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_LOGO.h"
#include "ui_MENU.h"
#include "ui_WIFI_MENU.h"
#include "ui_BLUETOOTH_MENU.h"
#include "ui_NFC_MENU.h"
#include "ui_RFID_MENU.h"
#include "ui_IR_MENU.h"
#include "ui_RF_MENU.h"
#include "ui_SCANNETWORKS.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * FadeIn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);    // assets/LOGO.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/WIFI.png
LV_IMG_DECLARE(ui_img_no_wifi_png);    // assets/NO WIFI.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/BLUETOOTH.png
LV_IMG_DECLARE(ui_img_no_bluetooth_png);    // assets/NO BLUETOOTH.png
LV_IMG_DECLARE(ui_img_nfc_png);    // assets/NFC.png
LV_IMG_DECLARE(ui_img_rfid_png);    // assets/RFID.png
LV_IMG_DECLARE(ui_img_ir_png);    // assets/IR.png
LV_IMG_DECLARE(ui_img_rf_png);    // assets/RF.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
