// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_BLUETOOTH_MENU_H
#define UI_BLUETOOTH_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BLUETOOTH_MENU
extern void ui_BLUETOOTH_MENU_screen_init(void);
extern void ui_BLUETOOTH_MENU_screen_destroy(void);
extern lv_obj_t * ui_BLUETOOTH_MENU;
extern lv_obj_t * ui_StatusBarBluetooth;
extern lv_obj_t * ui_BatteryTextBluetooth;
extern lv_obj_t * ui_WIFI3;
extern lv_obj_t * ui_NOWIFI3;
extern lv_obj_t * ui_BLUETOOTH3;
extern lv_obj_t * ui_NOBLUETOOTH3;
extern void ui_event_Back_Button2(lv_event_t * e);
extern lv_obj_t * ui_Back_Button2;
extern lv_obj_t * ui_Menu_Name2;
extern lv_obj_t * ui_Battery_Bar3;
extern lv_obj_t * ui_Bluetooth_Options;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

