// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_BLUETOOTH_MENU = NULL;
lv_obj_t * ui_StatusBarBluetooth = NULL;
lv_obj_t * ui_BatteryTextBluetooth = NULL;
lv_obj_t * ui_WIFI3 = NULL;
lv_obj_t * ui_NOWIFI3 = NULL;
lv_obj_t * ui_BLUETOOTH3 = NULL;
lv_obj_t * ui_NOBLUETOOTH3 = NULL;
lv_obj_t * ui_Back_Button2 = NULL;
lv_obj_t * ui_Menu_Name2 = NULL;
lv_obj_t * ui_Battery_Bar3 = NULL;
lv_obj_t * ui_Bluetooth_Options = NULL;
// event funtions
void ui_event_Back_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
    }
}

// build funtions

void ui_BLUETOOTH_MENU_screen_init(void)
{
    ui_BLUETOOTH_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLUETOOTH_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarBluetooth = lv_obj_create(ui_BLUETOOTH_MENU);
    lv_obj_remove_style_all(ui_StatusBarBluetooth);
    lv_obj_set_width(ui_StatusBarBluetooth, 241);
    lv_obj_set_height(ui_StatusBarBluetooth, 11);
    lv_obj_set_x(ui_StatusBarBluetooth, 0);
    lv_obj_set_y(ui_StatusBarBluetooth, -155);
    lv_obj_set_align(ui_StatusBarBluetooth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarBluetooth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarBluetooth, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarBluetooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextBluetooth = lv_label_create(ui_BLUETOOTH_MENU);
    lv_obj_set_width(ui_BatteryTextBluetooth, 52);
    lv_obj_set_height(ui_BatteryTextBluetooth, 13);
    lv_obj_set_x(ui_BatteryTextBluetooth, 87);
    lv_obj_set_y(ui_BatteryTextBluetooth, -154);
    lv_obj_set_align(ui_BatteryTextBluetooth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextBluetooth, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextBluetooth, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI3 = lv_img_create(ui_BLUETOOTH_MENU);
    lv_img_set_src(ui_WIFI3, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI3, 205);
    lv_obj_set_height(ui_WIFI3, 188);
    lv_obj_set_x(ui_WIFI3, -109);
    lv_obj_set_y(ui_WIFI3, -161);
    lv_obj_set_align(ui_WIFI3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI3, 14);

    ui_NOWIFI3 = lv_img_create(ui_BLUETOOTH_MENU);
    lv_img_set_src(ui_NOWIFI3, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI3, 201);
    lv_obj_set_height(ui_NOWIFI3, 194);
    lv_obj_set_x(ui_NOWIFI3, -111);
    lv_obj_set_y(ui_NOWIFI3, -158);
    lv_obj_set_align(ui_NOWIFI3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI3, 14);

    ui_BLUETOOTH3 = lv_img_create(ui_BLUETOOTH_MENU);
    lv_img_set_src(ui_BLUETOOTH3, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH3, 211);
    lv_obj_set_height(ui_BLUETOOTH3, 192);
    lv_obj_set_x(ui_BLUETOOTH3, -91);
    lv_obj_set_y(ui_BLUETOOTH3, -159);
    lv_obj_set_align(ui_BLUETOOTH3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH3, 14);

    ui_NOBLUETOOTH3 = lv_img_create(ui_BLUETOOTH_MENU);
    lv_img_set_src(ui_NOBLUETOOTH3, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH3, 199);
    lv_obj_set_height(ui_NOBLUETOOTH3, 199);
    lv_obj_set_x(ui_NOBLUETOOTH3, -97);
    lv_obj_set_y(ui_NOBLUETOOTH3, -156);
    lv_obj_set_align(ui_NOBLUETOOTH3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH3, 14);

    ui_Back_Button2 = lv_btn_create(ui_BLUETOOTH_MENU);
    lv_obj_set_width(ui_Back_Button2, 20);
    lv_obj_set_height(ui_Back_Button2, 20);
    lv_obj_set_x(ui_Back_Button2, -107);
    lv_obj_set_y(ui_Back_Button2, -136);
    lv_obj_set_align(ui_Back_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button2, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name2 = lv_label_create(ui_BLUETOOTH_MENU);
    lv_obj_set_width(ui_Menu_Name2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name2, 0);
    lv_obj_set_y(ui_Menu_Name2, -136);
    lv_obj_set_align(ui_Menu_Name2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name2, "BLUETOOTH MENU");
    lv_obj_set_style_text_decor(ui_Menu_Name2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar3 = lv_bar_create(ui_BLUETOOTH_MENU);
    lv_bar_set_value(ui_Battery_Bar3, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar3, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar3, 22);
    lv_obj_set_height(ui_Battery_Bar3, 9);
    lv_obj_set_x(ui_Battery_Bar3, 100);
    lv_obj_set_y(ui_Battery_Bar3, -155);
    lv_obj_set_align(ui_Battery_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar3, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar3, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar3, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar3, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bluetooth_Options = lv_dropdown_create(ui_BLUETOOTH_MENU);
    lv_dropdown_set_options(ui_Bluetooth_Options, "BLE Scanner\nPacket Sniffer\nSpoofer\nSpammer\nLog Devices");
    lv_obj_set_width(ui_Bluetooth_Options, 233);
    lv_obj_set_height(ui_Bluetooth_Options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bluetooth_Options, -1);
    lv_obj_set_y(ui_Bluetooth_Options, -103);
    lv_obj_set_align(ui_Bluetooth_Options, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bluetooth_Options, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_Back_Button2, ui_event_Back_Button2, LV_EVENT_ALL, NULL);

}

void ui_BLUETOOTH_MENU_screen_destroy(void)
{
    if(ui_BLUETOOTH_MENU) lv_obj_del(ui_BLUETOOTH_MENU);

    // NULL screen variables
    ui_BLUETOOTH_MENU = NULL;
    ui_StatusBarBluetooth = NULL;
    ui_BatteryTextBluetooth = NULL;
    ui_WIFI3 = NULL;
    ui_NOWIFI3 = NULL;
    ui_BLUETOOTH3 = NULL;
    ui_NOBLUETOOTH3 = NULL;
    ui_Back_Button2 = NULL;
    ui_Menu_Name2 = NULL;
    ui_Battery_Bar3 = NULL;
    ui_Bluetooth_Options = NULL;

}
