// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

// COMPONENT LogoImage

lv_obj_t * ui_LogoImage_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_LogoImage;
    cui_LogoImage = lv_img_create(comp_parent);
    lv_img_set_src(cui_LogoImage, &ui_img_logo_png);
    lv_obj_set_width(cui_LogoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LogoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_LogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_LogoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LOGOIMAGE_NUM);
    children[UI_COMP_LOGOIMAGE_LOGOIMAGE] = cui_LogoImage;
    lv_obj_add_event_cb(cui_LogoImage, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_LogoImage, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_LogoImage_create_hook(cui_LogoImage);
    return cui_LogoImage;
}

