// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_IR_MENU_H
#define UI_IR_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_IR_MENU
extern void ui_IR_MENU_screen_init(void);
extern void ui_IR_MENU_screen_destroy(void);
extern lv_obj_t * ui_IR_MENU;
extern lv_obj_t * ui_StatusBarIR;
extern lv_obj_t * ui_BatteryTextIR;
extern lv_obj_t * ui_WIFI6;
extern lv_obj_t * ui_NOWIFI6;
extern lv_obj_t * ui_BLUETOOTH6;
extern lv_obj_t * ui_NOBLUETOOTH6;
extern void ui_event_Back_Button5(lv_event_t * e);
extern lv_obj_t * ui_Back_Button5;
extern lv_obj_t * ui_Menu_Name5;
extern lv_obj_t * ui_Battery_Bar6;
extern lv_obj_t * ui_IR_Options;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

