// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_LOGO = NULL;
lv_obj_t * ui_LogoImage = NULL;
// event funtions
void ui_event_LOGO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_opacity_set(ui_LogoImage, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        FadeIn_Animation(ui_LogoImage, 3000);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 6000, &ui_MENU_screen_init);
    }
}

// build funtions

void ui_LOGO_screen_init(void)
{
    ui_LOGO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LOGO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LOGO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LOGO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImage = lv_img_create(ui_LOGO);
    lv_img_set_src(ui_LogoImage, &ui_img_logo_png);
    lv_obj_set_width(ui_LogoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_LOGO, ui_event_LOGO, LV_EVENT_ALL, NULL);

}

void ui_LOGO_screen_destroy(void)
{
    if(ui_LOGO) lv_obj_del(ui_LOGO);

    // NULL screen variables
    ui_LOGO = NULL;
    ui_LogoImage = NULL;

}
