// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_LOGO_H
#define UI_LOGO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LOGO
extern void ui_LOGO_screen_init(void);
extern void ui_LOGO_screen_destroy(void);
extern void ui_event_LOGO(lv_event_t * e);
extern lv_obj_t * ui_LOGO;
extern lv_obj_t * ui_LogoImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

