// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_NFC_MENU = NULL;
lv_obj_t * ui_StatusBarNFC = NULL;
lv_obj_t * ui_BatteryTextNFC = NULL;
lv_obj_t * ui_WIFI4 = NULL;
lv_obj_t * ui_NOWIFI4 = NULL;
lv_obj_t * ui_BLUETOOTH4 = NULL;
lv_obj_t * ui_NOBLUETOOTH4 = NULL;
lv_obj_t * ui_Back_Button3 = NULL;
lv_obj_t * ui_Menu_Name3 = NULL;
lv_obj_t * ui_Battery_Bar4 = NULL;
lv_obj_t * ui_NFC_Options = NULL;
// event funtions
void ui_event_Back_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
    }
}

// build funtions

void ui_NFC_MENU_screen_init(void)
{
    ui_NFC_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_NFC_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarNFC = lv_obj_create(ui_NFC_MENU);
    lv_obj_remove_style_all(ui_StatusBarNFC);
    lv_obj_set_width(ui_StatusBarNFC, 241);
    lv_obj_set_height(ui_StatusBarNFC, 11);
    lv_obj_set_x(ui_StatusBarNFC, 0);
    lv_obj_set_y(ui_StatusBarNFC, -155);
    lv_obj_set_align(ui_StatusBarNFC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarNFC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarNFC, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarNFC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextNFC = lv_label_create(ui_NFC_MENU);
    lv_obj_set_width(ui_BatteryTextNFC, 52);
    lv_obj_set_height(ui_BatteryTextNFC, 13);
    lv_obj_set_x(ui_BatteryTextNFC, 87);
    lv_obj_set_y(ui_BatteryTextNFC, -154);
    lv_obj_set_align(ui_BatteryTextNFC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextNFC, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextNFC, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI4 = lv_img_create(ui_NFC_MENU);
    lv_img_set_src(ui_WIFI4, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI4, 205);
    lv_obj_set_height(ui_WIFI4, 188);
    lv_obj_set_x(ui_WIFI4, -109);
    lv_obj_set_y(ui_WIFI4, -161);
    lv_obj_set_align(ui_WIFI4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI4, 14);

    ui_NOWIFI4 = lv_img_create(ui_NFC_MENU);
    lv_img_set_src(ui_NOWIFI4, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI4, 201);
    lv_obj_set_height(ui_NOWIFI4, 194);
    lv_obj_set_x(ui_NOWIFI4, -111);
    lv_obj_set_y(ui_NOWIFI4, -158);
    lv_obj_set_align(ui_NOWIFI4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI4, 14);

    ui_BLUETOOTH4 = lv_img_create(ui_NFC_MENU);
    lv_img_set_src(ui_BLUETOOTH4, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH4, 211);
    lv_obj_set_height(ui_BLUETOOTH4, 192);
    lv_obj_set_x(ui_BLUETOOTH4, -91);
    lv_obj_set_y(ui_BLUETOOTH4, -159);
    lv_obj_set_align(ui_BLUETOOTH4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH4, 14);

    ui_NOBLUETOOTH4 = lv_img_create(ui_NFC_MENU);
    lv_img_set_src(ui_NOBLUETOOTH4, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH4, 199);
    lv_obj_set_height(ui_NOBLUETOOTH4, 199);
    lv_obj_set_x(ui_NOBLUETOOTH4, -97);
    lv_obj_set_y(ui_NOBLUETOOTH4, -156);
    lv_obj_set_align(ui_NOBLUETOOTH4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH4, 14);

    ui_Back_Button3 = lv_btn_create(ui_NFC_MENU);
    lv_obj_set_width(ui_Back_Button3, 20);
    lv_obj_set_height(ui_Back_Button3, 20);
    lv_obj_set_x(ui_Back_Button3, -107);
    lv_obj_set_y(ui_Back_Button3, -136);
    lv_obj_set_align(ui_Back_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button3, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name3 = lv_label_create(ui_NFC_MENU);
    lv_obj_set_width(ui_Menu_Name3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name3, 0);
    lv_obj_set_y(ui_Menu_Name3, -136);
    lv_obj_set_align(ui_Menu_Name3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name3, "NFC MENU");
    lv_obj_set_style_text_decor(ui_Menu_Name3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar4 = lv_bar_create(ui_NFC_MENU);
    lv_bar_set_value(ui_Battery_Bar4, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar4, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar4, 22);
    lv_obj_set_height(ui_Battery_Bar4, 9);
    lv_obj_set_x(ui_Battery_Bar4, 100);
    lv_obj_set_y(ui_Battery_Bar4, -155);
    lv_obj_set_align(ui_Battery_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar4, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar4, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar4, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar4, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_NFC_Options = lv_dropdown_create(ui_NFC_MENU);
    lv_dropdown_set_options(ui_NFC_Options, "Read\nWrite\nEmulate\nSniffer\nMifare Attack\nDictionary Attack");
    lv_obj_set_width(ui_NFC_Options, 233);
    lv_obj_set_height(ui_NFC_Options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NFC_Options, -1);
    lv_obj_set_y(ui_NFC_Options, -103);
    lv_obj_set_align(ui_NFC_Options, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NFC_Options, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_Back_Button3, ui_event_Back_Button3, LV_EVENT_ALL, NULL);

}

void ui_NFC_MENU_screen_destroy(void)
{
    if(ui_NFC_MENU) lv_obj_del(ui_NFC_MENU);

    // NULL screen variables
    ui_NFC_MENU = NULL;
    ui_StatusBarNFC = NULL;
    ui_BatteryTextNFC = NULL;
    ui_WIFI4 = NULL;
    ui_NOWIFI4 = NULL;
    ui_BLUETOOTH4 = NULL;
    ui_NOBLUETOOTH4 = NULL;
    ui_Back_Button3 = NULL;
    ui_Menu_Name3 = NULL;
    ui_Battery_Bar4 = NULL;
    ui_NFC_Options = NULL;

}
