// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_RF_MENU_H
#define UI_RF_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RF_MENU
extern void ui_RF_MENU_screen_init(void);
extern void ui_RF_MENU_screen_destroy(void);
extern lv_obj_t * ui_RF_MENU;
extern lv_obj_t * ui_StatusBarRF;
extern lv_obj_t * ui_BatteryTextRF;
extern lv_obj_t * ui_WIFI7;
extern lv_obj_t * ui_NOWIFI7;
extern lv_obj_t * ui_BLUETOOTH7;
extern lv_obj_t * ui_NOBLUETOOTH7;
extern void ui_event_Back_Button6(lv_event_t * e);
extern lv_obj_t * ui_Back_Button6;
extern lv_obj_t * ui_Menu_Name6;
extern lv_obj_t * ui_Battery_Bar7;
extern lv_obj_t * ui_RF_Options;
extern void ui_event_Frequency(lv_event_t * e);
extern lv_obj_t * ui_Frequency;
extern lv_obj_t * ui_FrequencyDisplay;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

