// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_RF_MENU = NULL;
lv_obj_t * ui_StatusBarRF = NULL;
lv_obj_t * ui_BatteryTextRF = NULL;
lv_obj_t * ui_WIFI7 = NULL;
lv_obj_t * ui_NOWIFI7 = NULL;
lv_obj_t * ui_BLUETOOTH7 = NULL;
lv_obj_t * ui_NOBLUETOOTH7 = NULL;
lv_obj_t * ui_Back_Button6 = NULL;
lv_obj_t * ui_Menu_Name6 = NULL;
lv_obj_t * ui_Battery_Bar7 = NULL;
lv_obj_t * ui_RF_Options = NULL;
lv_obj_t * ui_Frequency = NULL;
lv_obj_t * ui_FrequencyDisplay = NULL;
// event funtions
void ui_event_Back_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
    }
}

void ui_event_Frequency(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_FrequencyDisplay, target, "915MHz", "433MHz");
    }
}

// build funtions

void ui_RF_MENU_screen_init(void)
{
    ui_RF_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RF_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarRF = lv_obj_create(ui_RF_MENU);
    lv_obj_remove_style_all(ui_StatusBarRF);
    lv_obj_set_width(ui_StatusBarRF, 241);
    lv_obj_set_height(ui_StatusBarRF, 11);
    lv_obj_set_x(ui_StatusBarRF, 0);
    lv_obj_set_y(ui_StatusBarRF, -155);
    lv_obj_set_align(ui_StatusBarRF, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarRF, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarRF, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarRF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextRF = lv_label_create(ui_RF_MENU);
    lv_obj_set_width(ui_BatteryTextRF, 52);
    lv_obj_set_height(ui_BatteryTextRF, 13);
    lv_obj_set_x(ui_BatteryTextRF, 87);
    lv_obj_set_y(ui_BatteryTextRF, -154);
    lv_obj_set_align(ui_BatteryTextRF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextRF, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextRF, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI7 = lv_img_create(ui_RF_MENU);
    lv_img_set_src(ui_WIFI7, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI7, 205);
    lv_obj_set_height(ui_WIFI7, 188);
    lv_obj_set_x(ui_WIFI7, -109);
    lv_obj_set_y(ui_WIFI7, -161);
    lv_obj_set_align(ui_WIFI7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI7, 14);

    ui_NOWIFI7 = lv_img_create(ui_RF_MENU);
    lv_img_set_src(ui_NOWIFI7, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI7, 201);
    lv_obj_set_height(ui_NOWIFI7, 194);
    lv_obj_set_x(ui_NOWIFI7, -111);
    lv_obj_set_y(ui_NOWIFI7, -158);
    lv_obj_set_align(ui_NOWIFI7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI7, 14);

    ui_BLUETOOTH7 = lv_img_create(ui_RF_MENU);
    lv_img_set_src(ui_BLUETOOTH7, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH7, 211);
    lv_obj_set_height(ui_BLUETOOTH7, 192);
    lv_obj_set_x(ui_BLUETOOTH7, -91);
    lv_obj_set_y(ui_BLUETOOTH7, -159);
    lv_obj_set_align(ui_BLUETOOTH7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH7, 14);

    ui_NOBLUETOOTH7 = lv_img_create(ui_RF_MENU);
    lv_img_set_src(ui_NOBLUETOOTH7, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH7, 199);
    lv_obj_set_height(ui_NOBLUETOOTH7, 199);
    lv_obj_set_x(ui_NOBLUETOOTH7, -97);
    lv_obj_set_y(ui_NOBLUETOOTH7, -156);
    lv_obj_set_align(ui_NOBLUETOOTH7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH7, 14);

    ui_Back_Button6 = lv_btn_create(ui_RF_MENU);
    lv_obj_set_width(ui_Back_Button6, 20);
    lv_obj_set_height(ui_Back_Button6, 20);
    lv_obj_set_x(ui_Back_Button6, -107);
    lv_obj_set_y(ui_Back_Button6, -136);
    lv_obj_set_align(ui_Back_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button6, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name6 = lv_label_create(ui_RF_MENU);
    lv_obj_set_width(ui_Menu_Name6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name6, 0);
    lv_obj_set_y(ui_Menu_Name6, -136);
    lv_obj_set_align(ui_Menu_Name6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name6, "RF MENU");
    lv_obj_set_style_text_decor(ui_Menu_Name6, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar7 = lv_bar_create(ui_RF_MENU);
    lv_bar_set_value(ui_Battery_Bar7, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar7, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar7, 22);
    lv_obj_set_height(ui_Battery_Bar7, 9);
    lv_obj_set_x(ui_Battery_Bar7, 100);
    lv_obj_set_y(ui_Battery_Bar7, -155);
    lv_obj_set_align(ui_Battery_Bar7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar7, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar7, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar7, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar7, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RF_Options = lv_dropdown_create(ui_RF_MENU);
    lv_dropdown_set_options(ui_RF_Options, "Spectrum Analyzer\nListen\nDecode\nReplay\nJammer\nTransmit");
    lv_obj_set_width(ui_RF_Options, 174);
    lv_obj_set_height(ui_RF_Options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RF_Options, -32);
    lv_obj_set_y(ui_RF_Options, -103);
    lv_obj_set_align(ui_RF_Options, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RF_Options, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Frequency = lv_switch_create(ui_RF_MENU);
    lv_obj_set_width(ui_Frequency, 50);
    lv_obj_set_height(ui_Frequency, 25);
    lv_obj_set_x(ui_Frequency, 87);
    lv_obj_set_y(ui_Frequency, -104);
    lv_obj_set_align(ui_Frequency, LV_ALIGN_CENTER);

    ui_FrequencyDisplay = lv_label_create(ui_RF_MENU);
    lv_obj_set_width(ui_FrequencyDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FrequencyDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FrequencyDisplay, 86);
    lv_obj_set_y(ui_FrequencyDisplay, -128);
    lv_obj_set_align(ui_FrequencyDisplay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FrequencyDisplay, "433MHz");
    lv_obj_clear_flag(ui_FrequencyDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Back_Button6, ui_event_Back_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Frequency, ui_event_Frequency, LV_EVENT_ALL, NULL);

}

void ui_RF_MENU_screen_destroy(void)
{
    if(ui_RF_MENU) lv_obj_del(ui_RF_MENU);

    // NULL screen variables
    ui_RF_MENU = NULL;
    ui_StatusBarRF = NULL;
    ui_BatteryTextRF = NULL;
    ui_WIFI7 = NULL;
    ui_NOWIFI7 = NULL;
    ui_BLUETOOTH7 = NULL;
    ui_NOBLUETOOTH7 = NULL;
    ui_Back_Button6 = NULL;
    ui_Menu_Name6 = NULL;
    ui_Battery_Bar7 = NULL;
    ui_RF_Options = NULL;
    ui_Frequency = NULL;
    ui_FrequencyDisplay = NULL;

}
