// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_RFID_MENU = NULL;
lv_obj_t * ui_StatusBarRFID = NULL;
lv_obj_t * ui_BatteryTextRFID = NULL;
lv_obj_t * ui_WIFI5 = NULL;
lv_obj_t * ui_NOWIFI5 = NULL;
lv_obj_t * ui_BLUETOOTH5 = NULL;
lv_obj_t * ui_NOBLUETOOTH5 = NULL;
lv_obj_t * ui_Back_Button4 = NULL;
lv_obj_t * ui_Menu_Name4 = NULL;
lv_obj_t * ui_Battery_Bar5 = NULL;
lv_obj_t * ui_RFID_Options = NULL;
// event funtions
void ui_event_Back_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
    }
}

// build funtions

void ui_RFID_MENU_screen_init(void)
{
    ui_RFID_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RFID_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarRFID = lv_obj_create(ui_RFID_MENU);
    lv_obj_remove_style_all(ui_StatusBarRFID);
    lv_obj_set_width(ui_StatusBarRFID, 241);
    lv_obj_set_height(ui_StatusBarRFID, 11);
    lv_obj_set_x(ui_StatusBarRFID, 0);
    lv_obj_set_y(ui_StatusBarRFID, -155);
    lv_obj_set_align(ui_StatusBarRFID, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarRFID, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarRFID, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarRFID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextRFID = lv_label_create(ui_RFID_MENU);
    lv_obj_set_width(ui_BatteryTextRFID, 52);
    lv_obj_set_height(ui_BatteryTextRFID, 13);
    lv_obj_set_x(ui_BatteryTextRFID, 87);
    lv_obj_set_y(ui_BatteryTextRFID, -154);
    lv_obj_set_align(ui_BatteryTextRFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextRFID, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextRFID, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI5 = lv_img_create(ui_RFID_MENU);
    lv_img_set_src(ui_WIFI5, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI5, 205);
    lv_obj_set_height(ui_WIFI5, 188);
    lv_obj_set_x(ui_WIFI5, -109);
    lv_obj_set_y(ui_WIFI5, -161);
    lv_obj_set_align(ui_WIFI5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI5, 14);

    ui_NOWIFI5 = lv_img_create(ui_RFID_MENU);
    lv_img_set_src(ui_NOWIFI5, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI5, 201);
    lv_obj_set_height(ui_NOWIFI5, 194);
    lv_obj_set_x(ui_NOWIFI5, -111);
    lv_obj_set_y(ui_NOWIFI5, -158);
    lv_obj_set_align(ui_NOWIFI5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI5, 14);

    ui_BLUETOOTH5 = lv_img_create(ui_RFID_MENU);
    lv_img_set_src(ui_BLUETOOTH5, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH5, 211);
    lv_obj_set_height(ui_BLUETOOTH5, 192);
    lv_obj_set_x(ui_BLUETOOTH5, -91);
    lv_obj_set_y(ui_BLUETOOTH5, -159);
    lv_obj_set_align(ui_BLUETOOTH5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH5, 14);

    ui_NOBLUETOOTH5 = lv_img_create(ui_RFID_MENU);
    lv_img_set_src(ui_NOBLUETOOTH5, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH5, 199);
    lv_obj_set_height(ui_NOBLUETOOTH5, 199);
    lv_obj_set_x(ui_NOBLUETOOTH5, -97);
    lv_obj_set_y(ui_NOBLUETOOTH5, -156);
    lv_obj_set_align(ui_NOBLUETOOTH5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH5, 14);

    ui_Back_Button4 = lv_btn_create(ui_RFID_MENU);
    lv_obj_set_width(ui_Back_Button4, 20);
    lv_obj_set_height(ui_Back_Button4, 20);
    lv_obj_set_x(ui_Back_Button4, -107);
    lv_obj_set_y(ui_Back_Button4, -136);
    lv_obj_set_align(ui_Back_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button4, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name4 = lv_label_create(ui_RFID_MENU);
    lv_obj_set_width(ui_Menu_Name4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name4, 0);
    lv_obj_set_y(ui_Menu_Name4, -136);
    lv_obj_set_align(ui_Menu_Name4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name4, "RFID MENU");
    lv_obj_set_style_text_decor(ui_Menu_Name4, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar5 = lv_bar_create(ui_RFID_MENU);
    lv_bar_set_value(ui_Battery_Bar5, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar5, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar5, 22);
    lv_obj_set_height(ui_Battery_Bar5, 9);
    lv_obj_set_x(ui_Battery_Bar5, 100);
    lv_obj_set_y(ui_Battery_Bar5, -155);
    lv_obj_set_align(ui_Battery_Bar5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar5, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar5, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar5, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar5, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RFID_Options = lv_dropdown_create(ui_RFID_MENU);
    lv_dropdown_set_options(ui_RFID_Options, "Test");
    lv_obj_set_width(ui_RFID_Options, 233);
    lv_obj_set_height(ui_RFID_Options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFID_Options, -1);
    lv_obj_set_y(ui_RFID_Options, -103);
    lv_obj_set_align(ui_RFID_Options, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RFID_Options, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_Back_Button4, ui_event_Back_Button4, LV_EVENT_ALL, NULL);

}

void ui_RFID_MENU_screen_destroy(void)
{
    if(ui_RFID_MENU) lv_obj_del(ui_RFID_MENU);

    // NULL screen variables
    ui_RFID_MENU = NULL;
    ui_StatusBarRFID = NULL;
    ui_BatteryTextRFID = NULL;
    ui_WIFI5 = NULL;
    ui_NOWIFI5 = NULL;
    ui_BLUETOOTH5 = NULL;
    ui_NOBLUETOOTH5 = NULL;
    ui_Back_Button4 = NULL;
    ui_Menu_Name4 = NULL;
    ui_Battery_Bar5 = NULL;
    ui_RFID_Options = NULL;

}
