// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_SCANNETWORKS = NULL;
lv_obj_t * ui_StatusBarRF2 = NULL;
lv_obj_t * ui_BatteryTextRF2 = NULL;
lv_obj_t * ui_WIFI8 = NULL;
lv_obj_t * ui_NOWIFI8 = NULL;
lv_obj_t * ui_BLUETOOTH8 = NULL;
lv_obj_t * ui_NOBLUETOOTH8 = NULL;
lv_obj_t * ui_Back_Button7 = NULL;
lv_obj_t * ui_Menu_Name7 = NULL;
lv_obj_t * ui_Battery_Bar8 = NULL;
lv_obj_t * ui_SelectSSID = NULL;
lv_obj_t * ui_ScanSSIDButton = NULL;
lv_obj_t * ui_ScanSSIDLabel = NULL;
lv_obj_t * ui_SSIDScanRoller = NULL;
// event funtions
void ui_event_SCANNETWORKS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScanNetworks(e);
    }
}

void ui_event_Back_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WIFI_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_WIFI_MENU_screen_init);
    }
}

void ui_event_SelectSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WIFI_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_WIFI_MENU_screen_init);
        RetrieveSSID(e);
    }
}

void ui_event_ScanSSIDButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ScanNetworks(e);
    }
}

// build funtions

void ui_SCANNETWORKS_screen_init(void)
{
    ui_SCANNETWORKS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCANNETWORKS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarRF2 = lv_obj_create(ui_SCANNETWORKS);
    lv_obj_remove_style_all(ui_StatusBarRF2);
    lv_obj_set_width(ui_StatusBarRF2, 241);
    lv_obj_set_height(ui_StatusBarRF2, 11);
    lv_obj_set_x(ui_StatusBarRF2, 0);
    lv_obj_set_y(ui_StatusBarRF2, -155);
    lv_obj_set_align(ui_StatusBarRF2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarRF2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarRF2, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarRF2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextRF2 = lv_label_create(ui_SCANNETWORKS);
    lv_obj_set_width(ui_BatteryTextRF2, 52);
    lv_obj_set_height(ui_BatteryTextRF2, 13);
    lv_obj_set_x(ui_BatteryTextRF2, 87);
    lv_obj_set_y(ui_BatteryTextRF2, -154);
    lv_obj_set_align(ui_BatteryTextRF2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextRF2, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextRF2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI8 = lv_img_create(ui_SCANNETWORKS);
    lv_img_set_src(ui_WIFI8, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI8, 205);
    lv_obj_set_height(ui_WIFI8, 188);
    lv_obj_set_x(ui_WIFI8, -109);
    lv_obj_set_y(ui_WIFI8, -161);
    lv_obj_set_align(ui_WIFI8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI8, 14);

    ui_NOWIFI8 = lv_img_create(ui_SCANNETWORKS);
    lv_img_set_src(ui_NOWIFI8, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI8, 201);
    lv_obj_set_height(ui_NOWIFI8, 194);
    lv_obj_set_x(ui_NOWIFI8, -111);
    lv_obj_set_y(ui_NOWIFI8, -158);
    lv_obj_set_align(ui_NOWIFI8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI8, 14);

    ui_BLUETOOTH8 = lv_img_create(ui_SCANNETWORKS);
    lv_img_set_src(ui_BLUETOOTH8, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH8, 211);
    lv_obj_set_height(ui_BLUETOOTH8, 192);
    lv_obj_set_x(ui_BLUETOOTH8, -91);
    lv_obj_set_y(ui_BLUETOOTH8, -159);
    lv_obj_set_align(ui_BLUETOOTH8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH8, 14);

    ui_NOBLUETOOTH8 = lv_img_create(ui_SCANNETWORKS);
    lv_img_set_src(ui_NOBLUETOOTH8, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH8, 199);
    lv_obj_set_height(ui_NOBLUETOOTH8, 199);
    lv_obj_set_x(ui_NOBLUETOOTH8, -97);
    lv_obj_set_y(ui_NOBLUETOOTH8, -156);
    lv_obj_set_align(ui_NOBLUETOOTH8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH8, 14);

    ui_Back_Button7 = lv_btn_create(ui_SCANNETWORKS);
    lv_obj_set_width(ui_Back_Button7, 20);
    lv_obj_set_height(ui_Back_Button7, 20);
    lv_obj_set_x(ui_Back_Button7, -107);
    lv_obj_set_y(ui_Back_Button7, -136);
    lv_obj_set_align(ui_Back_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button7, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name7 = lv_label_create(ui_SCANNETWORKS);
    lv_obj_set_width(ui_Menu_Name7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name7, 0);
    lv_obj_set_y(ui_Menu_Name7, -136);
    lv_obj_set_align(ui_Menu_Name7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name7, "SCAN NETWORKS");
    lv_obj_set_style_text_decor(ui_Menu_Name7, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar8 = lv_bar_create(ui_SCANNETWORKS);
    lv_bar_set_value(ui_Battery_Bar8, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar8, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar8, 22);
    lv_obj_set_height(ui_Battery_Bar8, 9);
    lv_obj_set_x(ui_Battery_Bar8, 100);
    lv_obj_set_y(ui_Battery_Bar8, -155);
    lv_obj_set_align(ui_Battery_Bar8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar8, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar8, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar8, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar8, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SelectSSID = lv_btn_create(ui_SCANNETWORKS);
    lv_obj_set_width(ui_SelectSSID, 20);
    lv_obj_set_height(ui_SelectSSID, 20);
    lv_obj_set_x(ui_SelectSSID, 107);
    lv_obj_set_y(ui_SelectSSID, -136);
    lv_obj_set_align(ui_SelectSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectSSID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectSSID, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanSSIDButton = lv_btn_create(ui_SCANNETWORKS);
    lv_obj_set_width(ui_ScanSSIDButton, 223);
    lv_obj_set_height(ui_ScanSSIDButton, 29);
    lv_obj_set_x(ui_ScanSSIDButton, 0);
    lv_obj_set_y(ui_ScanSSIDButton, -104);
    lv_obj_set_align(ui_ScanSSIDButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanSSIDButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanSSIDButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanSSIDButton, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanSSIDButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanSSIDLabel = lv_label_create(ui_ScanSSIDButton);
    lv_obj_set_width(ui_ScanSSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanSSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScanSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanSSIDLabel, "Scan");

    ui_SSIDScanRoller = lv_roller_create(ui_SCANNETWORKS);
    lv_obj_set_width(ui_SSIDScanRoller, 224);
    lv_obj_set_height(ui_SSIDScanRoller, 178);
    lv_obj_set_x(ui_SSIDScanRoller, 0);
    lv_obj_set_y(ui_SSIDScanRoller, 8);
    lv_obj_set_align(ui_SSIDScanRoller, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Back_Button7, ui_event_Back_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SelectSSID, ui_event_SelectSSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScanSSIDButton, ui_event_ScanSSIDButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SCANNETWORKS, ui_event_SCANNETWORKS, LV_EVENT_ALL, NULL);

}

void ui_SCANNETWORKS_screen_destroy(void)
{
    if(ui_SCANNETWORKS) lv_obj_del(ui_SCANNETWORKS);

    // NULL screen variables
    ui_SCANNETWORKS = NULL;
    ui_StatusBarRF2 = NULL;
    ui_BatteryTextRF2 = NULL;
    ui_WIFI8 = NULL;
    ui_NOWIFI8 = NULL;
    ui_BLUETOOTH8 = NULL;
    ui_NOBLUETOOTH8 = NULL;
    ui_Back_Button7 = NULL;
    ui_Menu_Name7 = NULL;
    ui_Battery_Bar8 = NULL;
    ui_SelectSSID = NULL;
    ui_ScanSSIDButton = NULL;
    ui_ScanSSIDLabel = NULL;
    ui_SSIDScanRoller = NULL;

}
