// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_SCANNETWORKS_H
#define UI_SCANNETWORKS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SCANNETWORKS
extern void ui_SCANNETWORKS_screen_init(void);
extern void ui_SCANNETWORKS_screen_destroy(void);
extern void ui_event_SCANNETWORKS(lv_event_t * e);
extern lv_obj_t * ui_SCANNETWORKS;
extern lv_obj_t * ui_StatusBarRF2;
extern lv_obj_t * ui_BatteryTextRF2;
extern lv_obj_t * ui_WIFI8;
extern lv_obj_t * ui_NOWIFI8;
extern lv_obj_t * ui_BLUETOOTH8;
extern lv_obj_t * ui_NOBLUETOOTH8;
extern void ui_event_Back_Button7(lv_event_t * e);
extern lv_obj_t * ui_Back_Button7;
extern lv_obj_t * ui_Menu_Name7;
extern lv_obj_t * ui_Battery_Bar8;
extern void ui_event_SelectSSID(lv_event_t * e);
extern lv_obj_t * ui_SelectSSID;
extern void ui_event_ScanSSIDButton(lv_event_t * e);
extern lv_obj_t * ui_ScanSSIDButton;
extern lv_obj_t * ui_ScanSSIDLabel;
extern lv_obj_t * ui_SSIDScanRoller;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

