// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#include "ui.h"

lv_obj_t * ui_WIFI_MENU = NULL;
lv_obj_t * ui_StatusBarWifi = NULL;
lv_obj_t * ui_BatteryTextWIFI = NULL;
lv_obj_t * ui_WIFI2 = NULL;
lv_obj_t * ui_NOWIFI2 = NULL;
lv_obj_t * ui_BLUETOOTH2 = NULL;
lv_obj_t * ui_NOBLUETOOTH2 = NULL;
lv_obj_t * ui_Back_Button = NULL;
lv_obj_t * ui_Menu_Name = NULL;
lv_obj_t * ui_Battery_Bar2 = NULL;
lv_obj_t * ui_WIFI_Options = NULL;
lv_obj_t * ui_WIFIKeyboard = NULL;
lv_obj_t * ui_ConnectNetworkContainer = NULL;
lv_obj_t * ui_ScanNetwork = NULL;
lv_obj_t * ui_ScanNetworkLabel = NULL;
lv_obj_t * ui_SSIDManual = NULL;
lv_obj_t * ui_PasswordManual = NULL;
lv_obj_t * ui_WIFIConnect = NULL;
lv_obj_t * ui_DumpFilesContainer = NULL;
lv_obj_t * ui_FilestoDump = NULL;
lv_obj_t * ui_FileDumpIP = NULL;
lv_obj_t * ui_ToggleFileServerSwitch = NULL;
lv_obj_t * ui_PacketMonitorContainer = NULL;
lv_obj_t * ui_PacketLoggerChart = NULL;
lv_obj_t * ui_PacketLogSwitch = NULL;
lv_obj_t * ui_DeviceInventoryContainer = NULL;
lv_obj_t * ui_DeviceInventoryRoller = NULL;
lv_obj_t * ui_DevicesFoundText = NULL;
lv_obj_t * ui_DeviceInventorySwitch = NULL;
lv_obj_t * ui_TargetMACButton = NULL;
lv_obj_t * ui_CaptivePortalContainer = NULL;
lv_obj_t * ui_CaptivePortalCredentialCount = NULL;
lv_obj_t * ui_ToggleCaptivePortalSwitch = NULL;
lv_obj_t * ui_BeaconSpammerContainer = NULL;
lv_obj_t * ui_NumSSIDsSpam = NULL;
lv_obj_t * ui_SpamType = NULL;
lv_obj_t * ui_SpamCount = NULL;
lv_obj_t * ui_EnableSSIDSpam = NULL;
lv_obj_t * ui_SSIDSpamSelect = NULL;
lv_obj_t * ui_MACSpooferContainer = NULL;
lv_obj_t * ui_CurrentMACLabel = NULL;
lv_obj_t * ui_SelectNewMAC = NULL;
lv_obj_t * ui_RandomMacButton = NULL;
lv_obj_t * ui_RandomizeSpoofText = NULL;
lv_obj_t * ui_StartSpoofingMACSwitch = NULL;
lv_obj_t * ui_DeauthenticatorContainer = NULL;
lv_obj_t * ui_TargetMACText = NULL;
lv_obj_t * ui_SelectFromInventoryButton = NULL;
lv_obj_t * ui_SelectFromInventoryText = NULL;
lv_obj_t * ui_DeauthAllCheckbox = NULL;
lv_obj_t * ui_DeauthSpeedSlider = NULL;
lv_obj_t * ui_DeauthButton = NULL;
lv_obj_t * ui_DeauthButtonText = NULL;
// event funtions
void ui_event_Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
    }
}

void ui_event_WIFI_Options(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        wifimenu_dropdown_handler(e);
    }
}

void ui_event_WIFIKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_WIFIKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScanNetwork(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SCANNETWORKS, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SCANNETWORKS_screen_init);
    }
}

void ui_event_SSIDManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_WIFIKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_WIFIKeyboard,  ui_SSIDManual);
    }
}

void ui_event_PasswordManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_WIFIKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_WIFIKeyboard,  ui_PasswordManual);
    }
}

void ui_event_WIFIConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WIFIConnectHandler(e);
    }
}

void ui_event_ToggleFileServerSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleFileDump(e);
    }
}

void ui_event_PacketLogSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TogglePacketLog(e);
    }
}

void ui_event_DeviceInventorySwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleDeviceInv(e);
    }
}

void ui_event_TargetMACButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TargetDeviceMAC(e);
    }
}

void ui_event_ToggleCaptivePortalSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleCaptivePortal(e);
    }
}

void ui_event_SpamCount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_NumSSIDsSpam, target, "", "");
    }
}

void ui_event_EnableSSIDSpam(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleSSIDSpam(e);
    }
}

void ui_event_SSIDSpamSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_WIFIKeyboard,  ui_SSIDSpamSelect);
        _ui_flag_modify(ui_WIFIKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_SelectNewMAC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_WIFIKeyboard,  ui_SelectNewMAC);
        _ui_flag_modify(ui_WIFIKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_RandomMacButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        RandomizeMAC(e);
    }
}

void ui_event_StartSpoofingMACSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        StartMACSpoofing(e);
    }
}

void ui_event_SelectFromInventoryButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DeviceInventoryContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DeauthenticatorContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DeauthButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartDeauth(e);
    }
}

// build funtions

void ui_WIFI_MENU_screen_init(void)
{
    ui_WIFI_MENU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WIFI_MENU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBarWifi = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_StatusBarWifi);
    lv_obj_set_width(ui_StatusBarWifi, 241);
    lv_obj_set_height(ui_StatusBarWifi, 11);
    lv_obj_set_x(ui_StatusBarWifi, 0);
    lv_obj_set_y(ui_StatusBarWifi, -155);
    lv_obj_set_align(ui_StatusBarWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBarWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StatusBarWifi, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBarWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryTextWIFI = lv_label_create(ui_WIFI_MENU);
    lv_obj_set_width(ui_BatteryTextWIFI, 52);
    lv_obj_set_height(ui_BatteryTextWIFI, 13);
    lv_obj_set_x(ui_BatteryTextWIFI, 87);
    lv_obj_set_y(ui_BatteryTextWIFI, -154);
    lv_obj_set_align(ui_BatteryTextWIFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextWIFI, "100%");
    lv_obj_set_style_text_font(ui_BatteryTextWIFI, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI2 = lv_img_create(ui_WIFI_MENU);
    lv_img_set_src(ui_WIFI2, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI2, 205);
    lv_obj_set_height(ui_WIFI2, 188);
    lv_obj_set_x(ui_WIFI2, -109);
    lv_obj_set_y(ui_WIFI2, -161);
    lv_obj_set_align(ui_WIFI2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI2, 14);

    ui_NOWIFI2 = lv_img_create(ui_WIFI_MENU);
    lv_img_set_src(ui_NOWIFI2, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_NOWIFI2, 201);
    lv_obj_set_height(ui_NOWIFI2, 194);
    lv_obj_set_x(ui_NOWIFI2, -111);
    lv_obj_set_y(ui_NOWIFI2, -158);
    lv_obj_set_align(ui_NOWIFI2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOWIFI2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOWIFI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOWIFI2, 14);

    ui_BLUETOOTH2 = lv_img_create(ui_WIFI_MENU);
    lv_img_set_src(ui_BLUETOOTH2, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_BLUETOOTH2, 211);
    lv_obj_set_height(ui_BLUETOOTH2, 192);
    lv_obj_set_x(ui_BLUETOOTH2, -91);
    lv_obj_set_y(ui_BLUETOOTH2, -159);
    lv_obj_set_align(ui_BLUETOOTH2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLUETOOTH2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLUETOOTH2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BLUETOOTH2, 14);

    ui_NOBLUETOOTH2 = lv_img_create(ui_WIFI_MENU);
    lv_img_set_src(ui_NOBLUETOOTH2, &ui_img_no_bluetooth_png);
    lv_obj_set_width(ui_NOBLUETOOTH2, 199);
    lv_obj_set_height(ui_NOBLUETOOTH2, 199);
    lv_obj_set_x(ui_NOBLUETOOTH2, -97);
    lv_obj_set_y(ui_NOBLUETOOTH2, -156);
    lv_obj_set_align(ui_NOBLUETOOTH2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NOBLUETOOTH2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NOBLUETOOTH2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NOBLUETOOTH2, 14);

    ui_Back_Button = lv_btn_create(ui_WIFI_MENU);
    lv_obj_set_width(ui_Back_Button, 20);
    lv_obj_set_height(ui_Back_Button, 20);
    lv_obj_set_x(ui_Back_Button, -107);
    lv_obj_set_y(ui_Back_Button, -136);
    lv_obj_set_align(ui_Back_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Back_Button, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Name = lv_label_create(ui_WIFI_MENU);
    lv_obj_set_width(ui_Menu_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Name, 0);
    lv_obj_set_y(ui_Menu_Name, -136);
    lv_obj_set_align(ui_Menu_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Name, "WIFI MENU");
    lv_obj_set_style_text_decor(ui_Menu_Name, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Bar2 = lv_bar_create(ui_WIFI_MENU);
    lv_bar_set_value(ui_Battery_Bar2, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Bar2, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Bar2, 22);
    lv_obj_set_height(ui_Battery_Bar2, 9);
    lv_obj_set_x(ui_Battery_Bar2, 100);
    lv_obj_set_y(ui_Battery_Bar2, -155);
    lv_obj_set_align(ui_Battery_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery_Bar2, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery_Bar2, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Battery_Bar2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Battery_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Battery_Bar2, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WIFI_Options = lv_dropdown_create(ui_WIFI_MENU);
    lv_dropdown_set_options(ui_WIFI_Options,
                            "Connect to a Network\nDump a File\nPacket Logging\nDevice Inventory\nCaptive Portal\nBeacon Spammer\nMAC Spoofer\nDeauthenticator");
    lv_obj_set_width(ui_WIFI_Options, 233);
    lv_obj_set_height(ui_WIFI_Options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFI_Options, -1);
    lv_obj_set_y(ui_WIFI_Options, -103);
    lv_obj_set_align(ui_WIFI_Options, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI_Options, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_WIFIKeyboard = lv_keyboard_create(ui_WIFI_MENU);
    lv_obj_set_width(ui_WIFIKeyboard, 233);
    lv_obj_set_height(ui_WIFIKeyboard, 120);
    lv_obj_set_x(ui_WIFIKeyboard, 0);
    lv_obj_set_y(ui_WIFIKeyboard, 98);
    lv_obj_set_align(ui_WIFIKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ConnectNetworkContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_ConnectNetworkContainer);
    lv_obj_set_width(ui_ConnectNetworkContainer, 234);
    lv_obj_set_height(ui_ConnectNetworkContainer, 231);
    lv_obj_set_x(ui_ConnectNetworkContainer, 0);
    lv_obj_set_y(ui_ConnectNetworkContainer, 32);
    lv_obj_set_align(ui_ConnectNetworkContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectNetworkContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ConnectNetworkContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanNetwork = lv_btn_create(ui_ConnectNetworkContainer);
    lv_obj_set_width(ui_ScanNetwork, 199);
    lv_obj_set_height(ui_ScanNetwork, 29);
    lv_obj_set_x(ui_ScanNetwork, -16);
    lv_obj_set_y(ui_ScanNetwork, 4);
    lv_obj_set_align(ui_ScanNetwork, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ScanNetwork, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanNetwork, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanNetworkLabel = lv_label_create(ui_ScanNetwork);
    lv_obj_set_width(ui_ScanNetworkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanNetworkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScanNetworkLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanNetworkLabel, "Scan Networks");

    ui_SSIDManual = lv_textarea_create(ui_ConnectNetworkContainer);
    lv_obj_set_width(ui_SSIDManual, 230);
    lv_obj_set_height(ui_SSIDManual, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_SSIDManual, -1);
    lv_obj_set_y(ui_SSIDManual, -56);
    lv_obj_set_align(ui_SSIDManual, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSIDManual, "SSID");
    lv_textarea_set_one_line(ui_SSIDManual, true);

    ui_PasswordManual = lv_textarea_create(ui_ConnectNetworkContainer);
    lv_obj_set_width(ui_PasswordManual, 230);
    lv_obj_set_height(ui_PasswordManual, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_PasswordManual, -1);
    lv_obj_set_y(ui_PasswordManual, -14);
    lv_obj_set_align(ui_PasswordManual, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordManual, "Password");
    lv_textarea_set_one_line(ui_PasswordManual, true);
    lv_textarea_set_password_mode(ui_PasswordManual, true);

    ui_WIFIConnect = lv_btn_create(ui_ConnectNetworkContainer);
    lv_obj_set_width(ui_WIFIConnect, 30);
    lv_obj_set_height(ui_WIFIConnect, 30);
    lv_obj_set_x(ui_WIFIConnect, 101);
    lv_obj_set_y(ui_WIFIConnect, -96);
    lv_obj_set_align(ui_WIFIConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIConnect, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DumpFilesContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_DumpFilesContainer);
    lv_obj_set_width(ui_DumpFilesContainer, 234);
    lv_obj_set_height(ui_DumpFilesContainer, 231);
    lv_obj_set_x(ui_DumpFilesContainer, 0);
    lv_obj_set_y(ui_DumpFilesContainer, 32);
    lv_obj_set_align(ui_DumpFilesContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DumpFilesContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DumpFilesContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FilestoDump = lv_dropdown_create(ui_DumpFilesContainer);
    lv_dropdown_set_options(ui_FilestoDump, "");
    lv_dropdown_set_text(ui_FilestoDump, "Select a File");
    lv_obj_set_width(ui_FilestoDump, 231);
    lv_obj_set_height(ui_FilestoDump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FilestoDump, 0);
    lv_obj_set_y(ui_FilestoDump, -95);
    lv_obj_set_align(ui_FilestoDump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FilestoDump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_FileDumpIP = lv_label_create(ui_DumpFilesContainer);
    lv_obj_set_width(ui_FileDumpIP, 223);
    lv_obj_set_height(ui_FileDumpIP, 21);
    lv_obj_set_x(ui_FileDumpIP, 0);
    lv_obj_set_y(ui_FileDumpIP, -59);
    lv_obj_set_align(ui_FileDumpIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FileDumpIP, "IP: Server Offline");

    ui_ToggleFileServerSwitch = lv_switch_create(ui_DumpFilesContainer);
    lv_obj_set_width(ui_ToggleFileServerSwitch, 50);
    lv_obj_set_height(ui_ToggleFileServerSwitch, 25);
    lv_obj_set_x(ui_ToggleFileServerSwitch, 70);
    lv_obj_set_y(ui_ToggleFileServerSwitch, -60);
    lv_obj_set_align(ui_ToggleFileServerSwitch, LV_ALIGN_CENTER);

    ui_PacketMonitorContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_PacketMonitorContainer);
    lv_obj_set_width(ui_PacketMonitorContainer, 234);
    lv_obj_set_height(ui_PacketMonitorContainer, 231);
    lv_obj_set_x(ui_PacketMonitorContainer, 0);
    lv_obj_set_y(ui_PacketMonitorContainer, 32);
    lv_obj_set_align(ui_PacketMonitorContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PacketMonitorContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PacketMonitorContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PacketLoggerChart = lv_chart_create(ui_PacketMonitorContainer);
    lv_obj_set_width(ui_PacketLoggerChart, 190);
    lv_obj_set_height(ui_PacketLoggerChart, 166);
    lv_obj_set_x(ui_PacketLoggerChart, 14);
    lv_obj_set_y(ui_PacketLoggerChart, 8);
    lv_obj_set_align(ui_PacketLoggerChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_PacketLoggerChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_PacketLoggerChart, 30);
    lv_chart_set_range(ui_PacketLoggerChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_PacketLoggerChart, 0, 5);
    lv_chart_set_axis_tick(ui_PacketLoggerChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 5, true, 50);
    lv_chart_set_axis_tick(ui_PacketLoggerChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 5, true, 50);
    lv_chart_set_axis_tick(ui_PacketLoggerChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);

    ui_PacketLogSwitch = lv_switch_create(ui_PacketMonitorContainer);
    lv_obj_set_width(ui_PacketLogSwitch, 50);
    lv_obj_set_height(ui_PacketLogSwitch, 25);
    lv_obj_set_x(ui_PacketLogSwitch, 82);
    lv_obj_set_y(ui_PacketLogSwitch, -98);
    lv_obj_set_align(ui_PacketLogSwitch, LV_ALIGN_CENTER);

    ui_DeviceInventoryContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_DeviceInventoryContainer);
    lv_obj_set_width(ui_DeviceInventoryContainer, 234);
    lv_obj_set_height(ui_DeviceInventoryContainer, 231);
    lv_obj_set_x(ui_DeviceInventoryContainer, 0);
    lv_obj_set_y(ui_DeviceInventoryContainer, 32);
    lv_obj_set_align(ui_DeviceInventoryContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeviceInventoryContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DeviceInventoryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DeviceInventoryRoller = lv_roller_create(ui_DeviceInventoryContainer);
    lv_obj_set_width(ui_DeviceInventoryRoller, 225);
    lv_obj_set_height(ui_DeviceInventoryRoller, 198);
    lv_obj_set_x(ui_DeviceInventoryRoller, 0);
    lv_obj_set_y(ui_DeviceInventoryRoller, 16);
    lv_obj_set_align(ui_DeviceInventoryRoller, LV_ALIGN_CENTER);

    ui_DevicesFoundText = lv_label_create(ui_DeviceInventoryContainer);
    lv_obj_set_width(ui_DevicesFoundText, 249);
    lv_obj_set_height(ui_DevicesFoundText, 17);
    lv_obj_set_x(ui_DevicesFoundText, 12);
    lv_obj_set_y(ui_DevicesFoundText, -101);
    lv_obj_set_align(ui_DevicesFoundText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevicesFoundText, "Devices Found: 0");

    ui_DeviceInventorySwitch = lv_switch_create(ui_DeviceInventoryContainer);
    lv_obj_set_width(ui_DeviceInventorySwitch, 50);
    lv_obj_set_height(ui_DeviceInventorySwitch, 25);
    lv_obj_set_x(ui_DeviceInventorySwitch, 53);
    lv_obj_set_y(ui_DeviceInventorySwitch, -101);
    lv_obj_set_align(ui_DeviceInventorySwitch, LV_ALIGN_CENTER);

    ui_TargetMACButton = lv_btn_create(ui_DeviceInventoryContainer);
    lv_obj_set_width(ui_TargetMACButton, 28);
    lv_obj_set_height(ui_TargetMACButton, 26);
    lv_obj_set_x(ui_TargetMACButton, 96);
    lv_obj_set_y(ui_TargetMACButton, -101);
    lv_obj_set_align(ui_TargetMACButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TargetMACButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TargetMACButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CaptivePortalContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_CaptivePortalContainer);
    lv_obj_set_width(ui_CaptivePortalContainer, 234);
    lv_obj_set_height(ui_CaptivePortalContainer, 231);
    lv_obj_set_x(ui_CaptivePortalContainer, 0);
    lv_obj_set_y(ui_CaptivePortalContainer, 32);
    lv_obj_set_align(ui_CaptivePortalContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CaptivePortalContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CaptivePortalContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CaptivePortalCredentialCount = lv_label_create(ui_CaptivePortalContainer);
    lv_obj_set_width(ui_CaptivePortalCredentialCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CaptivePortalCredentialCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CaptivePortalCredentialCount, -31);
    lv_obj_set_y(ui_CaptivePortalCredentialCount, -101);
    lv_obj_set_align(ui_CaptivePortalCredentialCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaptivePortalCredentialCount, "Credentials Logged: 0");

    ui_ToggleCaptivePortalSwitch = lv_switch_create(ui_CaptivePortalContainer);
    lv_obj_set_width(ui_ToggleCaptivePortalSwitch, 50);
    lv_obj_set_height(ui_ToggleCaptivePortalSwitch, 25);
    lv_obj_set_x(ui_ToggleCaptivePortalSwitch, 87);
    lv_obj_set_y(ui_ToggleCaptivePortalSwitch, -101);
    lv_obj_set_align(ui_ToggleCaptivePortalSwitch, LV_ALIGN_CENTER);

    ui_BeaconSpammerContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_BeaconSpammerContainer);
    lv_obj_set_width(ui_BeaconSpammerContainer, 234);
    lv_obj_set_height(ui_BeaconSpammerContainer, 231);
    lv_obj_set_x(ui_BeaconSpammerContainer, 0);
    lv_obj_set_y(ui_BeaconSpammerContainer, 32);
    lv_obj_set_align(ui_BeaconSpammerContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BeaconSpammerContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_BeaconSpammerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NumSSIDsSpam = lv_label_create(ui_BeaconSpammerContainer);
    lv_obj_set_width(ui_NumSSIDsSpam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumSSIDsSpam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumSSIDsSpam, 37);
    lv_obj_set_y(ui_NumSSIDsSpam, -62);
    lv_obj_set_align(ui_NumSSIDsSpam, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumSSIDsSpam, "0");

    ui_SpamType = lv_dropdown_create(ui_BeaconSpammerContainer);
    lv_dropdown_set_options(ui_SpamType, "Random SSIDs\nCustom SSID");
    lv_obj_set_width(ui_SpamType, 226);
    lv_obj_set_height(ui_SpamType, 36);
    lv_obj_set_x(ui_SpamType, 0);
    lv_obj_set_y(ui_SpamType, -94);
    lv_obj_set_align(ui_SpamType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpamType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SpamCount = lv_slider_create(ui_BeaconSpammerContainer);
    lv_slider_set_range(ui_SpamCount, 0, 20);
    lv_slider_set_value(ui_SpamCount, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SpamCount) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SpamCount, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpamCount, 123);
    lv_obj_set_height(ui_SpamCount, 7);
    lv_obj_set_x(ui_SpamCount, -45);
    lv_obj_set_y(ui_SpamCount, -63);
    lv_obj_set_align(ui_SpamCount, LV_ALIGN_CENTER);

    ui_EnableSSIDSpam = lv_switch_create(ui_BeaconSpammerContainer);
    lv_obj_set_width(ui_EnableSSIDSpam, 50);
    lv_obj_set_height(ui_EnableSSIDSpam, 25);
    lv_obj_set_x(ui_EnableSSIDSpam, 83);
    lv_obj_set_y(ui_EnableSSIDSpam, -60);
    lv_obj_set_align(ui_EnableSSIDSpam, LV_ALIGN_CENTER);

    ui_SSIDSpamSelect = lv_textarea_create(ui_BeaconSpammerContainer);
    lv_obj_set_width(ui_SSIDSpamSelect, 217);
    lv_obj_set_height(ui_SSIDSpamSelect, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_SSIDSpamSelect, 0);
    lv_obj_set_y(ui_SSIDSpamSelect, -22);
    lv_obj_set_align(ui_SSIDSpamSelect, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SSIDSpamSelect, "SSID");
    lv_textarea_set_one_line(ui_SSIDSpamSelect, true);
    lv_obj_add_flag(ui_SSIDSpamSelect, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_MACSpooferContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_MACSpooferContainer);
    lv_obj_set_width(ui_MACSpooferContainer, 234);
    lv_obj_set_height(ui_MACSpooferContainer, 231);
    lv_obj_set_x(ui_MACSpooferContainer, 0);
    lv_obj_set_y(ui_MACSpooferContainer, 32);
    lv_obj_set_align(ui_MACSpooferContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MACSpooferContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MACSpooferContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentMACLabel = lv_label_create(ui_MACSpooferContainer);
    lv_obj_set_width(ui_CurrentMACLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentMACLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentMACLabel, 0);
    lv_obj_set_y(ui_CurrentMACLabel, -101);
    lv_obj_set_align(ui_CurrentMACLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentMACLabel, "Current MAC: XX:XX:XX:XX:XX:XX");

    ui_SelectNewMAC = lv_textarea_create(ui_MACSpooferContainer);
    lv_obj_set_width(ui_SelectNewMAC, 226);
    lv_obj_set_height(ui_SelectNewMAC, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_SelectNewMAC, 0);
    lv_obj_set_y(ui_SelectNewMAC, -72);
    lv_obj_set_align(ui_SelectNewMAC, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_SelectNewMAC, "1234567890ABCDEF:");
    lv_textarea_set_max_length(ui_SelectNewMAC, 17);
    lv_textarea_set_placeholder_text(ui_SelectNewMAC, "New MAC: XX:XX:XX:XX:XX:XX");
    lv_textarea_set_one_line(ui_SelectNewMAC, true);

    ui_RandomMacButton = lv_btn_create(ui_MACSpooferContainer);
    lv_obj_set_width(ui_RandomMacButton, 140);
    lv_obj_set_height(ui_RandomMacButton, 25);
    lv_obj_set_x(ui_RandomMacButton, -42);
    lv_obj_set_y(ui_RandomMacButton, -34);
    lv_obj_set_align(ui_RandomMacButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RandomMacButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RandomMacButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RandomMacButton, lv_color_hex(0x9C9C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RandomMacButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RandomizeSpoofText = lv_label_create(ui_RandomMacButton);
    lv_obj_set_width(ui_RandomizeSpoofText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RandomizeSpoofText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RandomizeSpoofText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RandomizeSpoofText, "Random MAC");

    ui_StartSpoofingMACSwitch = lv_switch_create(ui_MACSpooferContainer);
    lv_obj_set_width(ui_StartSpoofingMACSwitch, 50);
    lv_obj_set_height(ui_StartSpoofingMACSwitch, 25);
    lv_obj_set_x(ui_StartSpoofingMACSwitch, 70);
    lv_obj_set_y(ui_StartSpoofingMACSwitch, -34);
    lv_obj_set_align(ui_StartSpoofingMACSwitch, LV_ALIGN_CENTER);

    ui_DeauthenticatorContainer = lv_obj_create(ui_WIFI_MENU);
    lv_obj_remove_style_all(ui_DeauthenticatorContainer);
    lv_obj_set_width(ui_DeauthenticatorContainer, 234);
    lv_obj_set_height(ui_DeauthenticatorContainer, 231);
    lv_obj_set_x(ui_DeauthenticatorContainer, 0);
    lv_obj_set_y(ui_DeauthenticatorContainer, 32);
    lv_obj_set_align(ui_DeauthenticatorContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeauthenticatorContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DeauthenticatorContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TargetMACText = lv_label_create(ui_DeauthenticatorContainer);
    lv_obj_set_width(ui_TargetMACText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetMACText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetMACText, -4);
    lv_obj_set_y(ui_TargetMACText, -101);
    lv_obj_set_align(ui_TargetMACText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetMACText, "Target MAC: XX:XX:XX:XX:XX:XX");

    ui_SelectFromInventoryButton = lv_btn_create(ui_DeauthenticatorContainer);
    lv_obj_set_width(ui_SelectFromInventoryButton, 220);
    lv_obj_set_height(ui_SelectFromInventoryButton, 27);
    lv_obj_set_x(ui_SelectFromInventoryButton, 0);
    lv_obj_set_y(ui_SelectFromInventoryButton, -74);
    lv_obj_set_align(ui_SelectFromInventoryButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectFromInventoryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectFromInventoryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectFromInventoryButton, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectFromInventoryButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectFromInventoryText = lv_label_create(ui_SelectFromInventoryButton);
    lv_obj_set_width(ui_SelectFromInventoryText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectFromInventoryText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SelectFromInventoryText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectFromInventoryText, "Select from Device Inventory");

    ui_DeauthAllCheckbox = lv_checkbox_create(ui_DeauthenticatorContainer);
    lv_checkbox_set_text(ui_DeauthAllCheckbox, "Kick All");
    lv_obj_set_width(ui_DeauthAllCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeauthAllCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeauthAllCheckbox, -71);
    lv_obj_set_y(ui_DeauthAllCheckbox, -38);
    lv_obj_set_align(ui_DeauthAllCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeauthAllCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_DeauthSpeedSlider = lv_slider_create(ui_DeauthenticatorContainer);
    lv_slider_set_value(ui_DeauthSpeedSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DeauthSpeedSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_DeauthSpeedSlider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_DeauthSpeedSlider, 113);
    lv_obj_set_height(ui_DeauthSpeedSlider, 10);
    lv_obj_set_x(ui_DeauthSpeedSlider, 45);
    lv_obj_set_y(ui_DeauthSpeedSlider, -39);
    lv_obj_set_align(ui_DeauthSpeedSlider, LV_ALIGN_CENTER);

    ui_DeauthButton = lv_btn_create(ui_DeauthenticatorContainer);
    lv_obj_set_width(ui_DeauthButton, 217);
    lv_obj_set_height(ui_DeauthButton, 50);
    lv_obj_set_x(ui_DeauthButton, 0);
    lv_obj_set_y(ui_DeauthButton, 6);
    lv_obj_set_align(ui_DeauthButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeauthButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeauthButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeauthButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeauthButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeauthButtonText = lv_label_create(ui_DeauthButton);
    lv_obj_set_width(ui_DeauthButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeauthButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DeauthButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeauthButtonText, "DEAUTHENTICATE");

    lv_obj_add_event_cb(ui_Back_Button, ui_event_Back_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WIFI_Options, ui_event_WIFI_Options, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_WIFIKeyboard, ui_SSIDManual);
    lv_obj_add_event_cb(ui_WIFIKeyboard, ui_event_WIFIKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScanNetwork, ui_event_ScanNetwork, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SSIDManual, ui_event_SSIDManual, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordManual, ui_event_PasswordManual, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WIFIConnect, ui_event_WIFIConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToggleFileServerSwitch, ui_event_ToggleFileServerSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PacketLogSwitch, ui_event_PacketLogSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeviceInventorySwitch, ui_event_DeviceInventorySwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TargetMACButton, ui_event_TargetMACButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToggleCaptivePortalSwitch, ui_event_ToggleCaptivePortalSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpamCount, ui_event_SpamCount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EnableSSIDSpam, ui_event_EnableSSIDSpam, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SSIDSpamSelect, ui_event_SSIDSpamSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SelectNewMAC, ui_event_SelectNewMAC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RandomMacButton, ui_event_RandomMacButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartSpoofingMACSwitch, ui_event_StartSpoofingMACSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SelectFromInventoryButton, ui_event_SelectFromInventoryButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeauthButton, ui_event_DeauthButton, LV_EVENT_ALL, NULL);

}

void ui_WIFI_MENU_screen_destroy(void)
{
    if(ui_WIFI_MENU) lv_obj_del(ui_WIFI_MENU);

    // NULL screen variables
    ui_WIFI_MENU = NULL;
    ui_StatusBarWifi = NULL;
    ui_BatteryTextWIFI = NULL;
    ui_WIFI2 = NULL;
    ui_NOWIFI2 = NULL;
    ui_BLUETOOTH2 = NULL;
    ui_NOBLUETOOTH2 = NULL;
    ui_Back_Button = NULL;
    ui_Menu_Name = NULL;
    ui_Battery_Bar2 = NULL;
    ui_WIFI_Options = NULL;
    ui_WIFIKeyboard = NULL;
    ui_ConnectNetworkContainer = NULL;
    ui_ScanNetwork = NULL;
    ui_ScanNetworkLabel = NULL;
    ui_SSIDManual = NULL;
    ui_PasswordManual = NULL;
    ui_WIFIConnect = NULL;
    ui_DumpFilesContainer = NULL;
    ui_FilestoDump = NULL;
    ui_FileDumpIP = NULL;
    ui_ToggleFileServerSwitch = NULL;
    ui_PacketMonitorContainer = NULL;
    ui_PacketLoggerChart = NULL;
    ui_PacketLogSwitch = NULL;
    ui_DeviceInventoryContainer = NULL;
    ui_DeviceInventoryRoller = NULL;
    ui_DevicesFoundText = NULL;
    ui_DeviceInventorySwitch = NULL;
    ui_TargetMACButton = NULL;
    ui_CaptivePortalContainer = NULL;
    ui_CaptivePortalCredentialCount = NULL;
    ui_ToggleCaptivePortalSwitch = NULL;
    ui_BeaconSpammerContainer = NULL;
    ui_NumSSIDsSpam = NULL;
    ui_SpamType = NULL;
    ui_SpamCount = NULL;
    ui_EnableSSIDSpam = NULL;
    ui_SSIDSpamSelect = NULL;
    ui_MACSpooferContainer = NULL;
    ui_CurrentMACLabel = NULL;
    ui_SelectNewMAC = NULL;
    ui_RandomMacButton = NULL;
    ui_RandomizeSpoofText = NULL;
    ui_StartSpoofingMACSwitch = NULL;
    ui_DeauthenticatorContainer = NULL;
    ui_TargetMACText = NULL;
    ui_SelectFromInventoryButton = NULL;
    ui_SelectFromInventoryText = NULL;
    ui_DeauthAllCheckbox = NULL;
    ui_DeauthSpeedSlider = NULL;
    ui_DeauthButton = NULL;
    ui_DeauthButtonText = NULL;

}
