// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Flipper Infinity Screen

#ifndef UI_WIFI_MENU_H
#define UI_WIFI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WIFI_MENU
extern void ui_WIFI_MENU_screen_init(void);
extern void ui_WIFI_MENU_screen_destroy(void);
extern lv_obj_t * ui_WIFI_MENU;
extern lv_obj_t * ui_StatusBarWifi;
extern lv_obj_t * ui_BatteryTextWIFI;
extern lv_obj_t * ui_WIFI2;
extern lv_obj_t * ui_NOWIFI2;
extern lv_obj_t * ui_BLUETOOTH2;
extern lv_obj_t * ui_NOBLUETOOTH2;
extern void ui_event_Back_Button(lv_event_t * e);
extern lv_obj_t * ui_Back_Button;
extern lv_obj_t * ui_Menu_Name;
extern lv_obj_t * ui_Battery_Bar2;
extern void ui_event_WIFI_Options(lv_event_t * e);
extern lv_obj_t * ui_WIFI_Options;
extern void ui_event_WIFIKeyboard(lv_event_t * e);
extern lv_obj_t * ui_WIFIKeyboard;
extern lv_obj_t * ui_ConnectNetworkContainer;
extern void ui_event_ScanNetwork(lv_event_t * e);
extern lv_obj_t * ui_ScanNetwork;
extern lv_obj_t * ui_ScanNetworkLabel;
extern void ui_event_SSIDManual(lv_event_t * e);
extern lv_obj_t * ui_SSIDManual;
extern void ui_event_PasswordManual(lv_event_t * e);
extern lv_obj_t * ui_PasswordManual;
extern void ui_event_WIFIConnect(lv_event_t * e);
extern lv_obj_t * ui_WIFIConnect;
extern lv_obj_t * ui_DumpFilesContainer;
extern lv_obj_t * ui_FilestoDump;
extern lv_obj_t * ui_FileDumpIP;
extern void ui_event_ToggleFileServerSwitch(lv_event_t * e);
extern lv_obj_t * ui_ToggleFileServerSwitch;
extern lv_obj_t * ui_PacketMonitorContainer;
extern lv_obj_t * ui_PacketLoggerChart;
extern void ui_event_PacketLogSwitch(lv_event_t * e);
extern lv_obj_t * ui_PacketLogSwitch;
extern lv_obj_t * ui_DeviceInventoryContainer;
extern lv_obj_t * ui_DeviceInventoryRoller;
extern lv_obj_t * ui_DevicesFoundText;
extern void ui_event_DeviceInventorySwitch(lv_event_t * e);
extern lv_obj_t * ui_DeviceInventorySwitch;
extern void ui_event_TargetMACButton(lv_event_t * e);
extern lv_obj_t * ui_TargetMACButton;
extern lv_obj_t * ui_CaptivePortalContainer;
extern lv_obj_t * ui_CaptivePortalCredentialCount;
extern void ui_event_ToggleCaptivePortalSwitch(lv_event_t * e);
extern lv_obj_t * ui_ToggleCaptivePortalSwitch;
extern lv_obj_t * ui_BeaconSpammerContainer;
extern lv_obj_t * ui_NumSSIDsSpam;
extern lv_obj_t * ui_SpamType;
extern void ui_event_SpamCount(lv_event_t * e);
extern lv_obj_t * ui_SpamCount;
extern void ui_event_EnableSSIDSpam(lv_event_t * e);
extern lv_obj_t * ui_EnableSSIDSpam;
extern void ui_event_SSIDSpamSelect(lv_event_t * e);
extern lv_obj_t * ui_SSIDSpamSelect;
extern lv_obj_t * ui_MACSpooferContainer;
extern lv_obj_t * ui_CurrentMACLabel;
extern void ui_event_SelectNewMAC(lv_event_t * e);
extern lv_obj_t * ui_SelectNewMAC;
extern void ui_event_RandomMacButton(lv_event_t * e);
extern lv_obj_t * ui_RandomMacButton;
extern lv_obj_t * ui_RandomizeSpoofText;
extern void ui_event_StartSpoofingMACSwitch(lv_event_t * e);
extern lv_obj_t * ui_StartSpoofingMACSwitch;
extern lv_obj_t * ui_DeauthenticatorContainer;
extern lv_obj_t * ui_TargetMACText;
extern void ui_event_SelectFromInventoryButton(lv_event_t * e);
extern lv_obj_t * ui_SelectFromInventoryButton;
extern lv_obj_t * ui_SelectFromInventoryText;
extern lv_obj_t * ui_DeauthAllCheckbox;
extern lv_obj_t * ui_DeauthSpeedSlider;
extern void ui_event_DeauthButton(lv_event_t * e);
extern lv_obj_t * ui_DeauthButton;
extern lv_obj_t * ui_DeauthButtonText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

